# theme: jekyll-theme-slate
remote_theme: pmarsceill/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: '/assets/images/logo.png'

# Color scheme supports "light" (default) and "dark"
color_scheme: custom
